sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development

addons:
  apt:
    packages:
      - mono-devel
      - mono-mcs  

install:
  # Install project dependencies
  - sudo apt-get install php5 -y
  - haxelib dev tink_core .
  #- haxelib install hxcpp
  #- haxelib install hxjava
  #- haxelib install hxcs

script:
  #- haxe tests/build-interp.hxml
  #- haxe tests/build-neko.hxml && neko bin/RunTests.n
  #- haxe tests/build-js.hxml && node bin/RunTests.js
  #- haxe tests/build-java.hxml && java -jar bin/java/RunTests.jar
  #- haxe tests/build-php.hxml && php bin/php/index.php
  #- haxe tests/build-cs.hxml && mono bin/cs/bin/RunTests.exe
  #- haxe tests/build-flash.hxml # Flash testing is hard to setup. Just run the haxe compiler for now
  #- haxe tests/build-cpp.hxml && ./bin/cpp/RunTests
  - haxe tests/build-python.hxml && python3 bin/RunTests.py
