sudo: required
dist: trusty

language: node_js
node_js: 8

os:
  - linux
  # - osx
    
install:
  - npm i -g lix
  - lix download
  - lix install gh:back2dos/travix

script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  - lix run travix node -D tink_core_no_error_pos
  # - lix run travix flash
  # - lix run travix java
  - lix run travix cpp
  - lix run travix cs
  - lix run travix php

env:
  secure: dhVtIkMcUYAyAK92oEzBiuHE2uH9MQ46PD8zdKnnky9WiH54x/Y167Wt1NvUhFxhNzfu44VpI5d1ngnSV5pwum+E/RfoJNoqIsRsy1dL/vnTwyBdGDwbBJc/RDqXYUQnF8okR3JBZKmr9FLXTl5DMKOP+mJE1IF6GLijTDR4pf8=

jobs:
  include:
    - stage: deploy
      os: linux
      haxe: "3.4.7"
      script: skip
      after_success:
        - haxelib install travix
        - lix run travix install
        - lix run travix release
