sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.3.0-rc.1
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=4.0.0-preview.4
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  - lix run travix interp
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  - lix run travix node -D tink_core_no_error_pos
  # - lix run travix flash
  # - lix run travix java
  - lix run travix cpp
  - lix run travix cs
  - lix run travix php

jobs:
  include:
    # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
    - stage: deploy
      language: haxe
      haxe: "3.4.7"
      os: linux
      install: skip
      script: skip
      env:
        secure: dhVtIkMcUYAyAK92oEzBiuHE2uH9MQ46PD8zdKnnky9WiH54x/Y167Wt1NvUhFxhNzfu44VpI5d1ngnSV5pwum+E/RfoJNoqIsRsy1dL/vnTwyBdGDwbBJc/RDqXYUQnF8okR3JBZKmr9FLXTl5DMKOP+mJE1IF6GLijTDR4pf8=
      after_success:
        - haxelib install travix
        - haxelib run travix install
        - haxelib run travix release
